/* auto-generated by NAPI-RS */
/* eslint-disable */

export class GP2FServer {
  constructor(config?: ServerConfig)
  get port(): number
  get isRunning(): boolean
  register(workflow: Workflow): void
  start(): Promise<void>
  stop(): Promise<void>
}

export class Workflow {
  constructor(workflowId: string)
  addActivity(name: string, config: ActivityConfig, onExecute?: (ctx: ExecutionContext) => Promise<void> | void): string
  get id(): string
  get activityCount(): number
  dryRun(state: any): boolean
}

export interface ActivityConfig {
  policy: AstNode
  compensationRef?: string
  isLocal?: boolean
}

export interface ServerConfig {
  port?: number
  host?: string
}

export interface ExecutionContext {
  instanceId: string
  tenantId: string
  activityName: string
  stateJson: string
}

export interface AstNode {
  kind: NodeKind
  children?: Array<AstNode>
  path?: string
  value?: string
  callName?: string
}

export type NodeKind =
  | 'LiteralTrue'
  | 'LiteralFalse'
  | 'And'
  | 'Or'
  | 'Not'
  | 'Eq'
  | 'Neq'
  | 'Gt'
  | 'Gte'
  | 'Lt'
  | 'Lte'
  | 'In'
  | 'Contains'
  | 'Exists'
  | 'Field'
  | 'Call'
  | 'VibeCheck'

export interface EvalResult {
  result: boolean
  trace: Array<string>
}

export function evaluate(policy: AstNode, state: any): boolean
export function evaluateWithTrace(policy: AstNode, state: any): EvalResult
